export type QuizQuestion = {
    question: string;
    options: string[];
    correctIndex: number;
};

export const QUIZ_DATA: Record<string, QuizQuestion[]> = {
    js: [
        { question: "Which keyword is used to declare a block-scoped variable that cannot be reassigned?", options: ["let", "var", "const", "def"], correctIndex: 2 },
        { question: "What is the output of 'typeof null'?", options: ["'object'", "'null'", "'undefined'", "'number'"], correctIndex: 0 },
        { question: "How do you check if a property exists in an object?", options: ["obj.has('prop')", "'prop' in obj", "obj.exists('prop')", "obj.contains('prop')"], correctIndex: 1 },
        { question: "Which method adds an element to the end of an array?", options: ["push()", "pop()", "shift()", "unshift()"], correctIndex: 0 },
        { question: "What does the '===' operator do?", options: ["Compares values only", "Assigns a value", "Compares values and types", "Compares types only"], correctIndex: 2 },
        { question: "Which function delays execution in JS?", options: ["setInterval()", "setTimeout()", "delay()", "sleep()"], correctIndex: 1 },
        { question: "What is a closure in JavaScript?", options: ["A function bundled with its lexical environment", "A closed browser window", "A locked variable", "A private class method"], correctIndex: 0 },
        { question: "How do you parse a JSON string into an object?", options: ["JSON.parse()", "JSON.stringify()", "JSON.object()", "JSON.toObj()"], correctIndex: 0 },
        { question: "What does Array.map() return?", options: ["A new array", "The original array", "A boolean", "A string"], correctIndex: 0 },
        { question: "Which keyword refers to the object the function is a property of?", options: ["that", "self", "this", "it"], correctIndex: 2 },
        { question: "How do you throw a custom error?", options: ["raise new Error('!')", "throw new Error('!')", "return new Error('!')", "yield new Error('!')"], correctIndex: 1 },
        { question: "What is the return value of 'Array.filter()'?", options: ["A single value", "A boolean", "A new array", "Undefined"], correctIndex: 2 },
        { question: "What is NaN?", options: ["Not a Number", "Null and Negative", "New Array Node", "None available Notes"], correctIndex: 0 },
        { question: "How can you freeze an object from being modified?", options: ["Object.lock()", "Object.freeze()", "Object.seal()", "Object.prevent()"], correctIndex: 1 },
        { question: "Which loops iterate over properties of an object?", options: ["for...of", "for...in", "while", "do...while"], correctIndex: 1 },
        { question: "What does 'use strict' do?", options: ["Enforces stricter parsing and error handling", "Speeds up code", "Includes standard libraries", "Makes HTML strictly typed"], correctIndex: 0 },
        { question: "What is event bubbling?", options: ["Events triggering from the target up to the root", "Events triggering from root down to target", "Events looping infinitely", "Events getting deleted"], correctIndex: 0 },
        { question: "What is a Promise in JS?", options: ["An object representing the eventual completion of an async operation", "A guarantee the code won't break", "A synchronous loop", "A strictly typed variable"], correctIndex: 0 },
        { question: "Which method removes the first element from an array?", options: ["pop()", "unshift()", "shift()", "splice()"], correctIndex: 2 },
        { question: "How to stop an event from bubbling up?", options: ["event.preventDefault()", "event.stopPropagation()", "event.cancel()", "event.stop()"], correctIndex: 1 },
        { question: "What is hoisting?", options: ["Lifting physical servers", "Declaring variables at the bottom", "Moving declarations to the top of the scope", "Erasing unused variables"], correctIndex: 2 },
        { question: "Which is true about 'const'?", options: ["It makes objects deeply immutable", "It prevents reassignment of the identifier", "It has global scope", "It is obsolete in ES6"], correctIndex: 1 },
        { question: "What is the difference between let and var?", options: ["let is block-scoped, var is function-scoped", "let is global, var is local", "They are identical", "let is strictly typed"], correctIndex: 0 },
        { question: "What is 'typeof undefined'?", options: ["'null'", "'undefined'", "'object'", "'string'"], correctIndex: 1 },
        { question: "What does 'Object.keys(obj)' return?", options: ["An array of the object's values", "A string of keys", "An array of the object's own enumerable property names", "A boolean"], correctIndex: 2 },
        { question: "What does 'Array.reduce()' do?", options: ["Deletes array elements", "Executes a reducer function resulting in a single output value", "Filters array elements", "Maps elements to DOM"], correctIndex: 1 },
        { question: "How do you select an element by ID?", options: ["document.getElementById('id')", "document.select('id')", "document.querySelector('.id')", "document.getId('id')"], correctIndex: 0 },
        { question: "Which function cancels a setTimeout?", options: ["clearTimeout()", "stopTimeout()", "removeTimeout()", "pauseTimeout()"], correctIndex: 0 },
        { question: "What is IIFE?", options: ["Inline Internal Function Expression", "Immediately Invoked Function Expression", "Internal Iterator For Each", "Inherited Instance For Events"], correctIndex: 1 },
        { question: "What symbol is used for rest parameters?", options: ["***", "...", "&&", "||"], correctIndex: 1 }
    ],
    ts: [
        { question: "What is TypeScript?", options: ["A database", "A typed superset of JavaScript", "A styling language", "A JS framework"], correctIndex: 1 },
        { question: "How do you specify a variable must be a string in TS?", options: ["let name: String", "let name: string", "String name", "string let name"], correctIndex: 1 },
        { question: "What does the 'any' type do?", options: ["Restricts to numbers", "Allows any type, bypassing checks", "Requires a specific format", "Triggers a compiler error"], correctIndex: 1 },
        { question: "How do you declare a custom type?", options: ["type MyType = ...", "class MyType = ...", "interface MyType == ...", "custom MyType = ..."], correctIndex: 0 },
        { question: "What is an interface?", options: ["A way to define the shape of an object", "A visual UI component", "A database connection", "A loop structure"], correctIndex: 0 },
        { question: "How do you make a property optional in an interface?", options: ["prop?: type", "prop!: type", "optional prop: type", "prop @type"], correctIndex: 0 },
        { question: "What does the 'unknown' type signify?", options: ["It's exactly like 'any'", "A type-safe counterpart to 'any'", "An error state", "A non-existent type"], correctIndex: 1 },
        { question: "What are generics used for?", options: ["Generating HTML", "Creating reusable components that work with a variety of types", "Generic error throwing", "Global variables"], correctIndex: 1 },
        { question: "Which utility type makes all properties of T optional?", options: ["Required<T>", "Omit<T>", "Partial<T>", "Optional<T>"], correctIndex: 2 },
        { question: "What does 'Readonly<T>' do?", options: ["Removes types", "Makes all properties of T read-only", "Hides properties", "Converts T to a string"], correctIndex: 1 },
        { question: "Which keyword creates an Enum?", options: ["enum", "enumerator", "list", "selection"], correctIndex: 0 },
        { question: "Can interfaces extend other interfaces?", options: ["Yes, using 'extends'", "Yes, using 'implements'", "No, only classes can", "No, interfaces are final"], correctIndex: 0 },
        { question: "What is a Tuple?", options: ["An array with known fixed length and types", "A nested object", "A specific string", "A boolean operator"], correctIndex: 0 },
        { question: "What utility selects specific properties from a Type?", options: ["Pick<T, K>", "Select<T, K>", "Omit<T, K>", "Extract<T, K>"], correctIndex: 0 },
        { question: "What utility removes specific properties from a Type?", options: ["Drop<T, K>", "Omit<T, K>", "Remove<T, K>", "Exclude<T, K>"], correctIndex: 1 },
        { question: "How do you cast a type in TS?", options: ["(val as Type)", "Type(val)", "val.make(Type)", "cast<Type>val"], correctIndex: 0 },
        { question: "What does 'never' define?", options: ["A constant", "A value that never occurs (e.g., error throwing functions)", "A global state", "Void return"], correctIndex: 1 },
        { question: "How do you define a union type?", options: ["type A | type B", "type A & type B", "type A + type B", "type A or type B"], correctIndex: 0 },
        { question: "What does the 'keyof' operator do?", options: ["Returns the object's values", "Yields a union of literal types representing keys", "Locks an object", "Encrypts a file"], correctIndex: 1 },
        { question: "Can TypeScript code run directly in a standard browser?", options: ["Yes", "No, it must be compiled/transpiled to JS", "Only in Chrome", "Only with plugins"], correctIndex: 1 },
        { question: "What is essentially a type guard?", options: ["A runtime check that narrows down a type", "A firewall for servers", "A strict TS config setting", "An anti-virus check"], correctIndex: 0 },
        { question: "What does 'Record<K, T>' do?", options: ["Records audio", "Constructs an object type whose property keys are K and values are T", "Logs errors to console", "Saves type history"], correctIndex: 1 },
        { question: "What is the '!' post-fix operator used for?", options: ["Non-null assertion", "Boolean NOT", "Factorial math", "Throwing errors instantly"], correctIndex: 0 },
        { question: "Which file configures the TS compiler?", options: ["tsconfig.json", "ts-config.js", "package.json", "types.ts"], correctIndex: 0 },
        { question: "What does 'Exclude<T, U>' do?", options: ["Includes U into T", "Excludes from T those types assignable to U", "Excludes the entire file", "Deletes a module"], correctIndex: 1 },
        { question: "How do you check if a variable 'x' is a specific class 'C'?", options: ["x is C", "x == C", "x instanceof C", "typeof x === C"], correctIndex: 2 },
        { question: "What is an intersection type?", options: ["Combines multiple types into one (Type A & Type B)", "Splits types", "Throws type errors", "Overwrites types"], correctIndex: 0 },
        { question: "What does the 'void' type indicate for a function?", options: ["It returns null", "It doesn't return a value", "It returns an empty string", "It deletes memory"], correctIndex: 1 },
        { question: "By default, what are the implicit types of function params?", options: ["any", "unknown", "string", "undefined"], correctIndex: 0 },
        { question: "How can you enable strict null checks?", options: ["strictNull=true", "strictNullChecks: true in tsconfig", "use strict null", "Not possible"], correctIndex: 1 }
    ],
    react: [
        { question: "What is React?", options: ["A database", "A JS library for building user interfaces", "A CSS framework", "A server engine"], correctIndex: 1 },
        { question: "What hook gets/sets state in a functional component?", options: ["useEffect", "useReducer", "useState", "useContext"], correctIndex: 2 },
        { question: "What does useEffect handle?", options: ["Routing", "DOM rendering", "Side effects in functional components", "Global state only"], correctIndex: 2 },
        { question: "What is JSX?", options: ["JavaScript XML", "Java Syntax Extension", "JSON X", "JavaScript XSS"], correctIndex: 0 },
        { question: "How do you pass data down to child components?", options: ["Using Context only", "Using Props", "Using Global vars", "Using State"], correctIndex: 1 },
        { question: "Which hook minimizes expensive calculations?", options: ["useMemo", "useCallback", "useRef", "useEffect"], correctIndex: 0 },
        { question: "Which hook memoizes functions?", options: ["useMemo", "useEffect", "useCallback", "useState"], correctIndex: 2 },
        { question: "What does a React Context do?", options: ["Replaces Redux entirely", "Lets you pass data deeply without prop drilling", "Handles HTTP requests", "Writes CSS"], correctIndex: 1 },
        { question: "What is a functional component?", options: ["A class extending React.Component", "A JS function that returns JSX", "An inner HTML tag", "A CSS module"], correctIndex: 1 },
        { question: "What happens if you leave out the dependency array in useEffect?", options: ["It never runs", "It runs once on mount", "It runs after every render", "It throws an error"], correctIndex: 2 },
        { question: "Why do mapped list items need a 'key' prop?", options: ["For CSS targeting", "To help React identify which items changed", "To execute click events", "To secure the DOM"], correctIndex: 1 },
        { question: "What hook gives direct access to a DOM node?", options: ["useEffect", "useContext", "useRef", "useDOM"], correctIndex: 2 },
        { question: "Can state mutation be synchronous in React 18?", options: ["Yes, always", "No, state updates are normally batched/asynchronous", "Only in dev mode", "Only with classes"], correctIndex: 1 },
        { question: "How do you wrap components to avoid extra DOM nodes?", options: ["<React.Fragment> or <>", "<div>", "<span>", "<React.Wrapper>"], correctIndex: 0 },
        { question: "What is 'prop drilling'?", options: ["Using electric tools", "Passing props through multiple layers of components", "A method to delete props", "CSS styling through props"], correctIndex: 1 },
        { question: "What does 'StrictMode' help with?", options: ["Highlighting potential problems in an application", "Making the app faster", "Enforcing TypeScript typing", "Blocking console logs"], correctIndex: 0 },
        { question: "What does 'ReactDOM.createRoot' do?", options: ["Deletes a root node", "Initializes the React 18 rendering tree", "Fetches data from an element", "Compiles JSX"], correctIndex: 1 },
        { question: "What is the virtual DOM?", options: ["A lightweight JS representation of the real DOM", "A VR headset feature", "A cloud server document", "An obsolete concept"], correctIndex: 0 },
        { question: "What is a Higher-Order Component (HOC)?", options: ["A function taking a component and returning a new component", "A component styled with Z-index", "A server component", "A hook"], correctIndex: 0 },
        { question: "Can you use hooks inside a standard JS nested if-statement?", options: ["Yes", "No, hooks must be called at the top level", "Only in Next.js", "Only if using let"], correctIndex: 1 },
        { question: "What returns when calling useState('hello')?", options: ["['hello']", "A getter function", "['hello', setterFunction]", "An object {val: 'hello'}"], correctIndex: 2 },
        { question: "What is the equivalent of 'componentDidMount' in hooks?", options: ["useEffect with missing array", "useEffect with [dependency]", "useEffect with []", "useState"], correctIndex: 2 },
        { question: "How to lazily load a React component?", options: ["React.lazy() and <Suspense>", "setTimeout", "React.delay()", "Dynamic fetch()"], correctIndex: 0 },
        { question: "What is the 'children' prop?", options: ["The state of the child", "Components passed between opening/closing tags", "Nested JSON data", "Component inheritance"], correctIndex: 1 },
        { question: "What is hydration?", options: ["Making components wet", "Attaching event listeners to server-rendered HTML", "Fetching initial API data", "Caching images"], correctIndex: 1 },
        { question: "What hook manages complex state objects similar to Redux?", options: ["useContext", "useState", "useReducer", "useComplex"], correctIndex: 2 },
        { question: "How to conditionally render <div/> if 'show' is true?", options: ["show ? <div/> : null", "if (show) <div/>", "show && <div/>", "Both A and C are common"], correctIndex: 3 },
        { question: "Can a child component mutate its props?", options: ["Yes directly", "No, props are read-only", "Only if it is a ref", "Only with CSS"], correctIndex: 1 },
        { question: "What does 'forwardRef' do?", options: ["Creates a ref", "Passes a ref through a component to a child", "Reverses a ref", "Deletes a ref"], correctIndex: 1 },
        { question: "What is synthetic event?", options: ["A fake event", "A cross-browser wrapper around browser native events", "A backend server hook", "A purely CSS action"], correctIndex: 1 }
    ],
    express: [
        { question: "What is Express.js?", options: ["A database", "A swift minimalist web framework for Node.js", "A frontend UI library", "A server operating system"], correctIndex: 1 },
        { question: "What is middleware?", options: ["Hardware connecting servers", "Functions that access req/res objects and the next() function", "A database query", "A frontend proxy"], correctIndex: 1 },
        { question: "How do you start an Express server listening?", options: ["app.run()", "app.listen()", "app.start()", "server.on()"], correctIndex: 1 },
        { question: "What does 'req.params' contain?", options: ["Query strings", "Route parameters", "The request body", "HTTP Headers"], correctIndex: 1 },
        { question: "What does 'req.query' contain?", options: ["Route parameters", "The parsed query string parameters", "JSON body", "Cookies"], correctIndex: 1 },
        { question: "How do you parse application/json bodies?", options: ["app.use(express.json())", "app.parseJson()", "req.json()", "express.body()"], correctIndex: 0 },
        { question: "What is the signature of an error-handling middleware?", options: ["(req, res, next)", "(error, req, res)", "(err, req, res, next)", "(res, req)"], correctIndex: 2 },
        { question: "How do you send a JSON response to the client?", options: ["res.sendJson()", "res.json()", "res.send()", "req.json()"], correctIndex: 1 },
        { question: "What does 'next()' do?", options: ["Returns a response", "Passes control to the next middleware function", "Restarts the server", "Skips a loop"], correctIndex: 1 },
        { question: "How do you define a GET route?", options: ["app.get('/path', handler)", "app.post('/path')", "app.receive('/path')", "app.route('/path').post()"], correctIndex: 0 },
        { question: "What is CORS?", options: ["Cross-Origin Resource Sharing", "Central Object Rendering Server", "Cascading Order Routing System", "Client Object Request System"], correctIndex: 0 },
        { question: "How do you serve static files in Express?", options: ["express.static()", "express.serve()", "app.files()", "express.send()"], correctIndex: 0 },
        { question: "Which method is typically used to update a resource?", options: ["GET", "PUT/PATCH", "DELETE", "OPTIONS"], correctIndex: 1 },
        { question: "What property holds data submitted in a POST request?", options: ["req.data", "req.form", "req.body", "req.post"], correctIndex: 2 },
        { question: "By default, does Express parse complex URL-encoded bodies?", options: ["Yes", "No, need express.urlencoded({extended: true})", "Only for nested JSON", "It happens automatically"], correctIndex: 1 },
        { question: "How do you handle a 404 block for undefined routes?", options: ["Put a catch-all app.use() at the very end", "Put a catch-all at the top", "Express does it automatically with custom HTML", "app.error404()"], correctIndex: 0 },
        { question: "What does Express use under the hood for HTTP?", options: ["The built-in Node 'http' module", "Fetch API", "Axios", "Nginx"], correctIndex: 0 },
        { question: "What is 'res.locals' used for?", options: ["Database credentials", "Passing state variables through middlewares to views", "Browser cache", "Logging"], correctIndex: 1 },
        { question: "Can a single route have multiple middleware callbacks?", options: ["No, only one", "Yes, arrays or multiple arguments can be used", "Only if it is a POST", "Only if using next()"], correctIndex: 1 },
        { question: "How do you redirect a user to another route?", options: ["res.send('/new')", "res.go('/new')", "res.redirect('/new')", "req.redirect('/new')"], correctIndex: 2 },
        { question: "What does 'res.sendStatus(200)' do?", options: ["Sets status to 200 and sends 'OK' body", "Throws an error", "Only sets headers but keeps conn open", "Sends nothing"], correctIndex: 0 },
        { question: "What is a dynamic routing segment?", options: ["A variable in the route path like '/users/:id'", "A random URL generator", "A WebSocket", "A floating IP"], correctIndex: 0 },
        { question: "What module typically helps parse cookies?", options: ["cookie-parser", "express-cookie", "cookie-reader", "npm-cookie"], correctIndex: 0 },
        { question: "What happens if a middleware doesn't call next() or send a response?", options: ["It auto-forwards", "The request hangs", "Express throws 500 error", "The client gets 404"], correctIndex: 1 },
        { question: "What is express.Router() primarily used for?", options: ["Rendering HTML", "Modular, mountable route handlers", "Connecting to SQL", "Sending emails"], correctIndex: 1 },
        { question: "What does app.route() do?", options: ["Creates chained route handlers for a specified path", "Generates URLs", "Starts a router server", "Registers global middleware"], correctIndex: 0 },
        { question: "Can Express integrate with templating engines like EJS/Pug?", options: ["No, only React", "Yes, using app.set('view engine')", "Only in Enterprise version", "Yes, using res.template()"], correctIndex: 1 },
        { question: "Which HTTP status code is for 'Internal Server Error'?", options: ["404", "403", "500", "200"], correctIndex: 2 },
        { question: "Which method is best to securely handle sensitive config tokens?", options: ["Hardcode in server.js", "req.headers", "Environment variables (dotenv)", "Query strings"], correctIndex: 2 },
        { question: "How to set an HTTP response header?", options: ["res.set('Header-Name', 'Value')", "req.setHeader()", "res.add()", "req.config()"], correctIndex: 0 }
    ],
    next: [
        { question: "What is Next.js primarily used for?", options: ["Building mobile apps", "Building full-stack React applications with SSR/SSG", "A database ORM", "A CSS preprocessor"], correctIndex: 1 },
        { question: "What is a Server Component in the App Router?", options: ["A Node.js backend script", "A component that renders exclusively on the server", "A React component executing only on the client", "A database schema"], correctIndex: 1 },
        { question: "How do you define a Client Component in App Router?", options: ["import 'client'", "module.exports = client", "'use client'", "'use browser'"], correctIndex: 2 },
        { question: "What is the role of 'layout.tsx'?", options: ["It defines UI shared across sub-segments", "It is only for mobile styling", "It parses API requests", "It renders the 404 page"], correctIndex: 0 },
        { question: "Which hook replaces useRouter() for navigation in the App Router?", options: ["from next/navigation", "from next/router", "useNavigate()", "useRoute()"], correctIndex: 0 },
        { question: "What is SSG?", options: ["Server Sent Game", "Static Site Generation", "Secure Server Guard", "Synchronous State Group"], correctIndex: 1 },
        { question: "What is SSR?", options: ["Server-Side Rendering", "Static Site React", "Secure Sockets Rendering", "Single State Render"], correctIndex: 0 },
        { question: "What component optimizes images in Next.js?", options: ["<Img />", "<NextImage />", "<Image />", "<Picture />"], correctIndex: 2 },
        { question: "How do you fetch data on the server in the App Router?", options: ["useFetch hook", "getStaticProps", "Using native async/await with fetch() directly in the component", "getServerSideProps"], correctIndex: 2 },
        { question: "What does 'next build' do?", options: ["Starts dev server", "Creates an optimized production build", "Lints your code", "Installs dependencies"], correctIndex: 1 },
        { question: "What does a 'loading.tsx' file do?", options: ["Shows an error boundary", "Displays instant fallback UI while a segment loads", "Creates a loading spinner globally only", "Prefetches data"], correctIndex: 1 },
        { question: "How can you create a dynamic route segment?", options: ["Folder named (slug)", "Folder named [id]", "File named route.ts", "File named index-[id].tsx"], correctIndex: 1 },
        { question: "What is the purpose of 'page.tsx'?", options: ["It renders shared layouts", "It's the unique UI of a specific route segment", "It controls middleware", "It hosts REST APIs"], correctIndex: 1 },
        { question: "Can a Client Component import a Server Component directly?", options: ["Yes, natively", "No, it must be passed as a 'children' prop", "Only if it is async", "Yes, but it converts to a Client component"], correctIndex: 1 },
        { question: "What does 'generateStaticParams' replace from the Pages router?", options: ["getServerSideProps", "getStaticPaths", "getInitialProps", "None of the above"], correctIndex: 1 },
        { question: "Which Next.js feature replaces a custom Express server for backend logic?", options: ["Route Handlers (route.ts)", "Middleware", "getStaticProps", "Layouts"], correctIndex: 0 },
        { question: "What is middleware in Next.js?", options: ["A file running before a request completes, useful for auth", "A component rendering phase", "A database interceptor", "A client-side hook"], correctIndex: 0 },
        { question: "What does the '<Link>' component do?", options: ["Prefetches routes in background for instant navigation", "Only applies CSS to anchors", "Links to external CSS logic", "Replaces standard JS imports"], correctIndex: 0 },
        { question: "How do you handle uncaught errors in an App Route segment?", options: ["Try/Catch only", "error.tsx file boundary", "fail.tsx", "Next.js handles it magically"], correctIndex: 1 },
        { question: "Can Server Components use 'useState'?", options: ["Yes", "No", "Only if they import React", "Only with 'use server'"], correctIndex: 1 },
        { question: "What happens if a component has no 'use client' directive in the App directory?", options: ["It defaults to a Client Component", "It defaults to a Server Component", "It throws an error", "It is ignored"], correctIndex: 1 },
        { question: "How to specify 'not found' UI for a route segment?", options: ["404.tsx", "not-found.tsx", "missing.tsx", "error.tsx"], correctIndex: 1 },
        { question: "What is standard caching behavior for native 'fetch' in Next.js Server Components?", options: ["It defaults to 'force-cache' (caches data)", "It defaults to 'no-store'", "It caches locally in the browser", "It depends on the component"], correctIndex: 0 },
        { question: "How to force a fetch to NEVER cache?", options: ["fetch(url, { cache: 'no-store' })", "fetch(url, { revalidate: 0 })", "Dynamic functions forcing dynamic rendering", "All of the above"], correctIndex: 3 },
        { question: "Which file defines global HTML tags like <html> and <body>?", options: ["global.tsx", "_app.tsx", "Root layout.tsx", "page.tsx"], correctIndex: 2 },
        { question: "What is ISR?", options: ["Incremental Static Regeneration", "Initial Server Route", "Internal System Renderer", "Immediate Static Response"], correctIndex: 0 },
        { question: "How does the App Router interpret folders starting with parentheses '(group)'?", options: ["As an API route", "As a Route Group that bypasses the URL structure", "As an ignored folder", "As a dynamic slug"], correctIndex: 1 },
        { question: "What's the default format Next.js uses for the App Router?", options: ["Pages format", "Rust format", "React Server Components (RSC)", "Client Components"], correctIndex: 2 },
        { question: "What component is used to inject third-party scripts efficiently?", options: ["<Script /> from next/script", "<link />", "<NextScript /> from config", "<Inject />"], correctIndex: 0 },
        { question: "Is Next.js built by Vercel?", options: ["Yes", "No", "It is built by Facebook", "It is built by Google"], correctIndex: 0 }
    ]
};
